package app;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import Atxy2k.CustomTextField.RestrictedTextField;

/**
 *
 * @author lalo Eduardo Nolasco P.
 */
public class pruebaConnection extends javax.swing.JFrame {
    Connect c = new Connect();
    PreparedStatement ps;
    ResultSet rs;
    private String day,dateAct,dateReg;
    
    private void limpiarCampos(){
        jTextField_id.setText(null);
        jTextField_nombre.setText(null);
        jTextField_apPat.setText(null);
        jTextField_apMat.setText(null);
        jComboBox_Genero.setSelectedIndex(0);
        dateReg=null;
    }

    /**
     * Creates new form pruebaConnection
     */
    public pruebaConnection() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Date fecha=new Date();
        SimpleDateFormat formatoDate = new SimpleDateFormat("YYYY-MM-dd");
        dateAct=formatoDate.format(fecha);
        SimpleDateFormat formatoDay = new SimpleDateFormat("dd");
        day=formatoDay.format(fecha);
        //SimpleDateFormat formatoNameWeek = new SimpleDateFormat("E"); resultado en letra
        SimpleDateFormat formatoNameWeek = new SimpleDateFormat("u"); //resultado en número
        System.out.println("El dia de la semana es: "+formatoNameWeek.format(fecha));
        System.out.println("Dia: "+day);
        System.out.println("Fecha: "+dateAct);
        
        String diaSub = dateAct.substring(8, 10);
        System.out.println("_"+diaSub+"_");
        
        
        RestrictedTextField idRTF = new RestrictedTextField(jTextField_id);
        idRTF.setLimit(3);
        //idRTF.setOnlyNums(true);
        RestrictedTextField nombreRTF = new RestrictedTextField(jTextField_nombre);
        nombreRTF.setLimit(25);
        //nombreRTF.setOnlyText(true);
        RestrictedTextField apPatRTF = new RestrictedTextField(jTextField_apPat);
        apPatRTF.setLimit(20);
        //apPatRTF.setOnlyText(true);
        RestrictedTextField apMatRTF = new RestrictedTextField(jTextField_apMat);
        apMatRTF.setLimit(20);
        //apMatRTF.setOnlyText(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_apPat = new javax.swing.JTextField();
        jTextField_apMat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Genero = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jToggleButtonMostrarDatos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id");

        jLabel2.setText("Nombre");

        jLabel3.setText("ap_pat");

        jLabel4.setText("ap_mat");

        jLabel5.setText("genero");

        jComboBox_Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Masculino", "Femenino" }));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_borrar.setText("Eliminar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        jToggleButtonMostrarDatos.setText("Mostrar todos los datos");
        jToggleButtonMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMostrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addComponent(jTextField_id))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_apPat))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_apMat, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jToggleButtonMostrarDatos)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_id)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btn_buscar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_nombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btn_guardar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_apPat)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(btn_modificar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_apMat)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(btn_borrar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar))
                .addGap(12, 12, 12)
                .addComponent(jToggleButtonMostrarDatos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        
        Connection con=null;
        try {
            con =c.getConnection();
            
            ps = con.prepareStatement("SELECT * FROM ejemplo WHERE id_ejem = ?");
            ps.setString(1, jTextField_id.getText());
            
            rs = ps.executeQuery();
            
            if (rs.next()) {
                jTextField_id.setText(rs.getString("id_ejem"));
                jTextField_nombre.setText(rs.getString("nombre"));
                jTextField_apPat.setText(rs.getString("ap_pat"));
                jTextField_apMat.setText(rs.getString("ap_mat"));
                jComboBox_Genero.setSelectedItem(rs.getString("genero"));
                dateReg=rs.getString("fecha");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron registros con esa clave");
                limpiarCampos();
            }
            c.desconectar();
            con.close();
            
        } catch (Exception e) {
            System.out.println("Error  \n"+e);
        }
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        Connection con=null;
        try {
            con = c.getConnection();
            
            ps = con.prepareStatement("INSERT INTO ejemplo (nombre, ap_pat, ap_mat, genero, fecha) VALUES (?,?,?,?,?)");
            ps.setString(1, jTextField_nombre.getText());
            ps.setString(2, jTextField_apPat.getText());
            ps.setString(3, jTextField_apMat.getText());
            ps.setString(4, jComboBox_Genero.getSelectedItem().toString());
            ps.setString(5, dateAct);
            
            int res =ps.executeUpdate();
            if (res>0) {
                JOptionPane.showMessageDialog(null, "Rejistro guardado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }
            limpiarCampos();
            c.desconectar();
            con.close();
            
        } catch (Exception e) {
            System.out.println("Error \n"+e);
        }
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        
        Connection con=null;
        try {
            con = c.getConnection();
            
            ps = con.prepareStatement("UPDATE ejemplo SET nombre=?, ap_pat=?, ap_mat=?, genero=?, fecha=? WHERE id_ejem=?");
            ps.setString(1, jTextField_nombre.getText());
            ps.setString(2, jTextField_apPat.getText());
            ps.setString(3, jTextField_apMat.getText());
            ps.setString(4, jComboBox_Genero.getSelectedItem().toString());
            
            String inDate=JOptionPane.showInputDialog("Deceas modificar la fecha\n Formato: YYYY-MM-DD", dateReg);
            if (inDate!=null) {
                ps.setString(5, inDate);
            } else {
                ps.setString(5, dateReg);
            }        
                    
            ps.setString(6, jTextField_id.getText());
            
            
            int res =ps.executeUpdate();
            if (res>0) {
                JOptionPane.showMessageDialog(null, "Rejistro modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }
            limpiarCampos();
            c.desconectar();
            con.close();
            
        } catch (Exception e) {
            System.out.println("Error \n"+e);
        }
        
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        
        Connection con=null;
        try {
            con = c.getConnection();
            
            ps = con.prepareStatement("DELETE FROM ejemplo WHERE id_ejem=?");
            ps.setString(1, jTextField_id.getText());
            
            int res =ps.executeUpdate();
            if (res>0) {
                JOptionPane.showMessageDialog(null, "Rejistro eliminado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar registro");
            }
            limpiarCampos();
            c.desconectar();
            con.close();
            
        } catch (Exception e) {
            System.out.println("Error \n"+e);
        }
        
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void jToggleButtonMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarDatosActionPerformed
        VerDatos MTD = new VerDatos();
        MTD.setVisible(true);
    }//GEN-LAST:event_jToggleButtonMostrarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebaConnection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> jComboBox_Genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField_apMat;
    private javax.swing.JTextField jTextField_apPat;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JToggleButton jToggleButtonMostrarDatos;
    // End of variables declaration//GEN-END:variables
}
